[project]
name = "elecciones-bonaerenses-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.7"
dependencies = [
    "selenium>=4.35.0",
    "tenacity>=9.1.2",
    "tqdm>=4.67.1",
    "undetected-chromedriver>=3.5.5",
]
